class CellDetector:
    def __init__(self, width, height, start_z, connect_type=4): ...
    def process(self, layer) -> None: ...
    def get_coords_list(self): ...

def get_structure_centre_wrapper(structure): ...
