#!/bin/sh
# Builds HTML and PDF documentation and adds to the commit.
# Runs before every commit
echo "Running pre-commit hooks"
echo

## Docs #####################################################
echo "Building HTML docs"
make -C doc_build/ html
echo "Building PDF docs"
make -C doc_build/ latexpdf
echo "Build complete"
echo
echo "Copying docs to final location"
cp doc_build/_build/latex/cellfinder.pdf ./cellfinder.pdf
cp -rfT doc_build/_build/html docs
echo
echo "Adding docs to commit"
echo
git add doc_build docs/* cellfinder.pdf
git add -u doc_build docs
echo "Have a nice day!"
echo
##############################################################